### ISSUE TITLE
why only green?

### ISSUE THREAD

**Issue by XsFrozdY** [thewaiter/MokshaGreen#1]
could we get this in at least RGB?
(totally new to linux, so customizing things is hard to get into, so having already made ones would be quite convenient for us newbies that just wants minimal work to setup).

**Comment by thewaiter** [comment]
Hello there
I am sorry but I have some difficulties to understand your point. This is a e17 default theme derivate with green color (that's why it is called MokshaGreen). Please try to be more detailed in your request...
Stefan

**Comment by XsFrozdY** [comment]
what I mean is; why only JUST MokshaGreen? why not MokshaBlue and Red at least, preferably all major colors, so on top RGB (Red, green and blue), there could be pink, purple, lime, cyan, yellow, orange, white, grey, I hope you get the idea.

JUST green is too limiting, it might be the official color or whatever, doesn't matter, everyone might like the overall design of it, I DO like the overall design, but I HATE the color, so more options would be appreciated

**Comment by thewaiter** [comment]
Have you checked all our maintained themes? It looks you haven't. You have all colors included to your taste

**Comment by XsFrozdY** [comment]
i have, even have arc dark applied, but, that one only have partial icon make over and I HATE the blue annoying border                          around the windows and have a few other gripes with it too, so yeah, certainly been through them all and MokshaGreen is the one I want, but in blue because of the coherent icons, overall synergy with the overall look and feel and so on.

**Comment by XsFrozdY** [comment]
wouldn't be here moaning about it otherwise

**Comment by thewaiter** [comment]
You can easily remove the blue frame around the focused window in ArcDark. Anyway, I do not consider this to be a good place for chat. Join us on official forums. This is no theme issue, but a request. I am about to close this thread.
